### ISSUE TITLE
Change hover colour of 'Go' button to maintain styling consistency.

### ISSUE THREAD

**Issue by apoorvsxna** [apoorvsxna/youtube-playlist-length#1]
* It would be better to have a different color when hovering over the 'Go' button to make it more legible.

* Current Behaviour-
 
![Screenshot (111)](https://github.com/apoorvsxna/youtube-playlist-length/assets/112375644/ce024259-ef7b-4124-96b8-ca9991314029)

**Comment by Arnav-Saxena** [comment]
Can you please assign this issue to me?
This would require modifying the `background-color` in `button:hover` in the styles.css file, right?

**Comment by apoorvsxna** [comment]
> Can you please assign this issue to me? This would require modifying the `background-color` in `button:hover` in the styles.css file, right?

Yes, that's correct. Assigned.
